const studentDetailsValues = [
  {
    firstName: "HelloWorld",
    lastName: "123-123",
    email: "12@3",
    phone: "123",
    address: "111 Northwood Rd",
    location: "Melbourne",
    marks: { eng: "111", math: "222", science: "100", computers: "100" },
  },
  {
    firstName: "DomoArigatou",
    lastName: "Do itshimashite",
    email: "22@2",
    phone: "222",
    address: "123 W Virfinia",
    location: "Kansas City",
    marks: { eng: "222", math: "333", science: "100", computers: "100" },
  },
  {
    firstName: "Avrakadavra",
    lastName: "inspecto petronum",
    email: "0@90",
    phone: "090",
    address: "29 Baker Street",
    location: "London",
    marks: { eng: "100", math: "102", science: "100", computers: "100" },
  },
  {
    firstName: "ads",
    lastName: "asnum",
    email: "0asd@90",
    phone: "091231310",
    address: "29 Baker Street",
    location: "Istanbul",
    marks: { eng: "100", math: "102", science: "100", computers: "100" },
  },
  {
    firstName: "Avrakadavra",
    lastName: "inspecto petronum",
    email: "012@asd90",
    phone: "091112120",
    address: "29 Baker Street",
    location: "Dubai",
    marks: { eng: "100", math: "102", science: "100", computers: "100" },
  },
  {
    firstName: "Avrakadavra",
    lastName: "inspecto petronum",
    email: "09@120",
    phone: "0127790",
    address: "29 Baker Street",
    location: "New Delhi",
    marks: { eng: "100", math: "102", science: "100", computers: "100" },
  },
  {
    firstName: "HelloWorld",
    lastName: "123-123",
    email: "12@3",
    phone: "123",
    address: "111 Northwood Rd",
    location: "Melbourne",
    marks: { eng: "111", math: "222", science: "100", computers: "100" },
  },
  {
    firstName: "DomoArigatou",
    lastName: "Do itshimashite",
    email: "22@2",
    phone: "222",
    address: "123 W Virfinia",
    location: "Kansas City",
    marks: { eng: "222", math: "333", science: "100", computers: "100" },
  },
  {
    firstName: "Avrakadavra",
    lastName: "inspecto petronum",
    email: "0@90",
    phone: "090",
    address: "29 Baker Street",
    location: "London",
    marks: { eng: "100", math: "102", science: "100", computers: "100" },
  },
  {
    firstName: "ads",
    lastName: "asnum",
    email: "0asd@90",
    phone: "091231310",
    address: "29 Baker Street",
    location: "Istanbul",
    marks: { eng: "100", math: "102", science: "100", computers: "100" },
  },
];

export default studentDetailsValues;
